package tdlm;

/**
 * This class provides the properties that are needed to be loaded for setting
 * up To Do List Maker workspace controls including language-dependent text.
 *
 * @author Richard McKenna
 * @version 1.0
 */
public enum ToDoPropertyType {

    /* THESE ARE THE NODES IN OUR APP */
    // THIS IS THE TDLM WORKSPACE PANE
    TDLM_PANE,
    TDLM_TO_DO_LIST_LABEL,
    
    // THIS IS THE DETAILS PANE
    TDLM_NAME_OWNER_PANE,
    TDLM_OWNER_PANE,
    TDLM_OWNER_LABEL,
    TDLM_OWNER_TEXT_FIELD,
    // THIS IS THE DETAILS PANE
    TDLM_NAME_NAME_PANE,
    TDLM_NAME_PANE,
    TDLM_NAME_LABEL,
    TDLM_NAME_TEXT_FIELD,
    
    // ITEMS EDITING
    TDLM_ITEMS_PANE,
    TDLM_ITEM_BUTTONS_PANE,
    TDLM_ADD_ITEM_BUTTON,
    TDLM_REMOVE_ITEM_BUTTON,
    TDLM_EDIT_ITEM_BUTTON,
    TDLM_MOVE_UP_ITEM_BUTTON,
    TDLM_MOVE_DOWN_ITEM_BUTTON,
    TDLM_ITEMS_TABLE_VIEW,
    TDLM_CATEGORY_COLUMN,
    TDLM_DESCRIPTION_COLUMN,
    TDLM_START_DATE_COLUMN,
    TDLM_END_DATE_COLUMN,
    TDLM_ASSIGNED_TO_COLUMN,
    TDLM_COMPLETED_COLUMN,
    
    // FOOLPROOF SETTINGS
    TDLM_FOOLPROOF_SETTINGS,
    
    // DIALOG CONTROLS
    TDLM_ITEM_DIALOG_HEADER,
    TDLM_ITEM_DIALOG_ADD_HEADER_TEXT,
    TDLM_ITEM_DIALOG_EDIT_HEADER_TEXT,
    TDLM_ITEM_DIALOG_CATEGORY_PROMPT,
    TDLM_ITEM_DIALOG_CATEGORY_TEXT_FIELD,
    TDLM_ITEM_DIALOG_DESCRIPTION_PROMPT,
    TDLM_ITEM_DIALOG_DESCRIPTION_TEXT_FIELD,
    TDLM_ITEM_DIALOG_START_DATE_PROMPT,
    TDLM_ITEM_DIALOG_START_DATE_PICKER,
    TDLM_ITEM_DIALOG_END_DATE_PROMPT,
    TDLM_ITEM_DIALOG_END_DATE_PICKER,
    TDLM_ITEM_DIALOG_ASSIGNED_TO_PROMPT,
    TDLM_ITEM_DIALOG_ASSIGNED_TO_TEXT_FIELD,
    TDLM_ITEM_DIALOG_COMPLETED_PROMPT,
    TDLM_ITEM_DIALOG_COMPLETED_CHECK_BOX,
    TDLM_ITEM_DIALOG_CONFIRM_PANE,
    TDLM_ITEM_DIALOG_OK_BUTTON,
    TDLM_ITEM_DIALOG_CANCEL_BUTTON,
    
    // ERROR DIALOGS
    TDLM_ERROR_CATEGORY_TEXT,
    TDLM_ERROR_DESCRIPTION_TEXT,
    TDLM_ERROR_DATE_TEXT,
    
    // THIS IS THE EXPORT TEMPLATE FILE NAME
    TDLM_EXPORT_TEMPLATE_FILE_NAME
}
